# Generated by Django 6.0.4 on 2026-04-20 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статус сделки',
                'verbose_name_plural': 'Статусы сделок',
                'db_table': 'deal_statuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'db_table': 'task_statuses',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='propertyphoto',
            options={'ordering': ['-is_cover', 'order', '-uploaded_at'], 'verbose_name': 'Фото объекта', 'verbose_name_plural': 'Фото объектов'},
        ),
        migrations.RenameField(
            model_name='house',
            old_name='fias_id',
            new_name='external_id',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='fias_id',
            new_name='external_id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='fias_id',
        ),
        migrations.AddField(
            model_name='city',
            name='external_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Внешний идентификатор адресного реестра (из DaData)', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='deal',
            name='contract_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='key.request'),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/'),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_requests', to='key.property'),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'employee'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('client', 'Клиент')], default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='key.dealstatus'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий')], default='normal', max_length=10)),
                ('task_type', models.CharField(choices=[('contact_client', 'Связаться с клиентом'), ('property_search', 'Подбор объектов'), ('showing', 'Показ объекта'), ('documents', 'Подготовка документов'), ('call', 'Звонок'), ('other', 'Прочее')], db_index=True, default='other', max_length=30)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, help_text='Результат выполнения задачи', null=True)),
                ('is_auto_closed', models.BooleanField(default=False, help_text='Закрыта автоматически системой')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(limit_choices_to={'user_type': 'employee'}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='key.deal')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='key.property')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='key.request')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='key.taskstatus')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='key.property')),
                ('recipient', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_emails', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='key.request')),
                ('sender', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='key.task')),
            ],
            options={
                'verbose_name': 'Исходящее письмо',
                'verbose_name_plural': 'Исходящие письма',
                'db_table': 'outgoing_emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestPropertyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_note', models.TextField(blank=True, null=True)),
                ('is_offered', models.BooleanField(default=True, help_text='Предложено клиенту')),
                ('is_rejected', models.BooleanField(default=False, help_text='Клиент отказался')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type': 'employee'}, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_matches', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_matches', to='key.property')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='key.request')),
            ],
            options={
                'verbose_name': 'Вариант по заявке',
                'verbose_name_plural': 'Варианты по заявкам',
                'db_table': 'request_property_matches',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('request', 'property'), name='unique_request_property_match')],
            },
        ),
    ]
