# Generated by Django
"""
Миграция для задачи 7:
- Добавление полей task_type, result, is_auto_closed в Task
- Создание модели OutgoingEmail для исходящих писем
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0004_propertyphoto_hidden_order'),
    ]

    operations = [
        # Добавляем поле task_type в Task
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(
                choices=[
                    ('contact_client', 'Связаться с клиентом'),
                    ('property_search', 'Подбор объектов'),
                    ('showing', 'Показ объекта'),
                    ('documents', 'Подготовка документов'),
                    ('call', 'Звонок'),
                    ('other', 'Прочее'),
                ],
                db_index=True,
                default='other',
                max_length=30,
            ),
        ),
        # Добавляем поле result в Task
        migrations.AddField(
            model_name='task',
            name='result',
            field=models.TextField(
                blank=True,
                help_text='Результат выполнения задачи',
                null=True,
            ),
        ),
        # Добавляем поле is_auto_closed в Task
        migrations.AddField(
            model_name='task',
            name='is_auto_closed',
            field=models.BooleanField(
                default=False,
                help_text='Закрыта автоматически системой',
            ),
        ),
        # Создаём модель OutgoingEmail
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Ожидает отправки'),
                        ('sent', 'Отправлено'),
                        ('failed', 'Ошибка отправки'),
                    ],
                    db_index=True,
                    default='pending',
                    max_length=20,
                )),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='emails',
                    to='key.property',
                )),
                ('recipient', models.ForeignKey(
                    limit_choices_to={'user_type': 'client'},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='outgoing_emails',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('request', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='emails',
                    to='key.request',
                )),
                ('sender', models.ForeignKey(
                    blank=True,
                    limit_choices_to={'user_type': 'employee'},
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sent_emails',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('task', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='emails',
                    to='key.task',
                )),
            ],
            options={
                'db_table': 'outgoing_emails',
                'ordering': ['-created_at'],
                'verbose_name': 'Исходящее письмо',
                'verbose_name_plural': 'Исходящие письма',
            },
        ),
    ]
